# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: NovaMindLab.ShareCLIP
PackageVersion: 4.5.9
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/NovaMindLab/AIShare-Grabber/releases/download/v4.5.9/ShareCLIP-Setup-4.5.9.exe
    InstallerSha256: 18753C62A64607557281ED9D7363CF5CC3868A87E658BFC4233C3544D28ED6E1
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
