# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: NovaMindLab.ShareCLIP
PackageVersion: 4.5.8
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/NovaMindLab/AIShare-Grabber/releases/download/v4.5.8/ShareCLIP-Setup-4.5.8.exe
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
