import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static const String _keyLang = 'pref_app_language';
  String _currentLocale = 'en'; // Defaults to English!

  LocalizationService() {
    _loadLanguage();
  }

  String get currentLocale => _currentLocale;

  static final Map<String, String> languages = {
    'en': 'English',
    'zh': '简体中文',
    'zh-TW': '繁體中文',
    'ja': '日本語',
    'ko': '한국어',
    'es': 'Español',
    'fr': 'Français',
    'de': 'Deutsch',
    'it': 'Italiano',
    'ru': 'Русский',
    'pt': 'Português',
    'vi': 'Tiếng Việt',
    'th': 'ไทย',
    'id': 'Bahasa Indonesia',
    'ar': 'العربية',
    'hi': 'हिन्दी',
    'tr': 'Türkçe',
    'pl': 'Polski',
    'nl': 'Nederlands',
    'sv': 'Svenska'
  };

  static final Map<String, Map<String, String>> _locales = {
    'en': {
      // Navigation & Shell
      'homeTitle': 'ShareCLIP Companion',
      'navLink': 'Link',
      'navMedia': 'Media',
      'navAi': 'AI Album',
      'navSettings': 'Settings',
      'aiCategories': 'categories',
      'aiNotSynced': 'PC AI vectors not synced yet',
      'syncAiVectors': 'Sync AI Vectors',
      'syncing': 'Syncing...',
      'aiThreshold': 'Similarity Threshold',
      'aiThresholdControl': 'Category Freedom (Threshold)',
      'aiMoreMatches': 'More matches (0.15)',
      'aiHigherPrecision': 'Higher precision (0.45)',
      'aiNoCategoryPhotos': 'No photos matched in this category',
      'aiTryAdjustThreshold': 'Try lowering the similarity threshold above',
      'aiWelcomeTitle': 'AI Smart Album Classification',
      'aiWelcomeDesc': 'No AI inference on phone! Connect to PC and sync precomputed classification vectors to browse categories freely.',
      'syncAiVectorsNow': 'Sync AI Vectors Now',
      'aiConnectPcFirst': 'Connect to PC first to sync AI vectors',
      'disconnected': 'Disconnected',
      'connected': 'Connected',
      'linkPc': 'Scan QR to Connect',
      'linkPcDesc': 'Scan the PC QR code to start syncing',
      'scanToConnect': 'Scan to Connect',
      'localMedia': 'Local Gallery',
      'items': 'items',
      'photos': 'Photos',
      'videos': 'Videos',
      'music': 'Music',
      'docs': 'Docs',
      'queue': 'Queue',
      'noPhotos': 'No photos found',
      'noVideos': 'No videos found',
      'noMusic': 'No music tracks found',
      'noDocs': 'No documents chosen',
      'pickDocs': 'Pick Document Files',
      'back': 'Back',
      'backHome': 'Back to Home',
      'cancel': 'Cancel',
      'retry': 'Retry Pairing',

      // Permissions
      'permissionTitle': 'Permission Required',
      'permissionDesc': 'ShareCLIP uses the camera to scan connection QR codes and Bluetooth/Wi-Fi to discover and pair with the desktop application.',
      'grantBtn': 'Grant Permissions',
      'cameraPermRequired': 'Please grant camera permissions in settings to scan QR codes',
      'cameraInitFailed': 'Camera initialization failed: {error}',

      // Connection Status & Steps
      'connecting': 'Connecting PC...',
      'connectingDesc': 'Exchanging WebRTC parameters via BLE GATT signaling channel.',
      'connFailed': 'Connection Failed',
      'connFailedDesc': 'Could not pair with PC. Please check Bluetooth and Wi-Fi configurations.',
      'secureP2p': 'Secure P2P Sync',
      'stepPairing': 'Discovery & Pairing',
      'stepSignaling': 'Handshake',
      'stepTunnel': 'P2P Direct',
      'statusDiscovering': 'Discovering PC via LAN & Bluetooth...',
      'statusMtu': 'Negotiating high-speed parameters (MTU)...',
      'statusGatt': 'Establishing secure service channel...',
      'statusCrypto': 'Generating WebRTC direct crypto offer...',
      'statusOffer': 'Syncing handshake offer to PC...',
      'statusAnswer': 'Awaiting remote PC confirmation...',
      'statusTunnel': 'Building P2P high-speed WebRTC tunnel...',
      'statusPreparing': 'Preparing connection...',

      // Scanner & LAN
      'scannerBanner': 'Align the PC QR code inside the frame',
      'scanTitle': 'Scan to Connect',
      'scanSubTip': 'Align the PC QR code inside the frame to connect instantly',
      'pickFromGallery': 'Album QR',
      'torch': 'Flashlight',
      'flip': 'Flip Camera',
      'lanPcFound': 'LAN PCs Nearby',
      'instantConnect': 'Connect',
      'qrNotFound': 'No QR code found in the selected image',

      // Settings & Theme
      'settingsTitle': 'Settings & Appearance',
      'themeMode': 'Theme Mode',
      'themeLight': 'Clear Light',
      'themeDark': 'Midnight Dark',
      'themeOcean': 'Deep Ocean',
      'themeAmoled': 'AMOLED Pure',
      'themeCyberpunk': 'Cyberpunk',
      'languageSettings': 'Language',
      'selectLanguage': 'Select Language',
      'currentLanguage': 'Current Language',

      // Transfer Console & Sync Hub
      'tabMedia': 'Media',
      'tabAi': 'AI Album',
      'tabMusic': 'Music',
      'tabDocs': 'Docs',
      'tabQueue': 'Queue',
      'aiVectorSyncTitle': 'Sync PC AI Vectors & Categories',
      'aiVectorSyncDesc': 'Pull computed AI categories and feature vectors from PC for offline instant filtering and category freedom.',
      'syncAiVectorsBtn': 'Sync AI Vectors Now',
      'syncingAiVectors': 'Syncing AI Vectors from PC...',
      'send': 'Send',
      'receiving': 'Receiving file...',
      'transmitting': 'Transmitting file...',
      'queueEmpty': 'No active transfers',
      'selectedPhotos': 'Selected Photos',
      'selectedVideos': 'Selected Videos',
      'selectedMusic': 'Selected Music',
      'selectFilesHint': 'Browse other tabs to select files to transmit',
      'syncHub': 'Multi-Device Sync Hub',
      'syncHubDesc': 'Cross-Device Data Sync & AI Categorization',
      'aiSyncTitle': 'AI Album Categorization (MobileCLIP)',
      'aiSyncDesc': 'Sync thumbnails to PC for zero-shot local AI classification',
      'aiSyncProgress': 'AI Syncing: {done}/{total}',
      'aiSyncDone': 'AI Sync Complete',
      'syncSelectedToAi': 'Sync Selected ({count}) Images to AI',
      'syncAllToAi': 'Sync All Images to AI',
      'albumBackupTitle': 'Full Album Backup to PC',
      'albumBackupDesc': 'Transfer all original photos & videos over local P2P',
      'albumBackupProgress': 'Full Backup: {done}/{total} ({percent}%)',
      'albumBackupDone': 'Full Backup Complete',
      'resumeBackup': 'Resume',
      'pauseBackup': 'Pause',
      'stopBackup': 'Stop',
      'startAlbumBackup': 'Start Full Album Backup',
      'resumeAlbumSync': 'Resume Album Sync',
      'startVideoBackup': 'Backup All Videos to PC',
      'resumeVideoSync': 'Resume Video Sync',
      'startMusicBackup': 'Backup All Music to PC',
      'resumeMusicSync': 'Resume Music Sync',

      // App Update & Downloader
      'updateTitle': 'Update Available',
      'updateSubtitle': 'A new version of ShareCLIP is ready',
      'updateMessage': 'A new version of ShareCLIP (v{version}) is available. Upgrade now for the latest features and stability improvements.',
      'updateHighlights': '⚡ High-Speed Direct P2P & MobileCLIP AI\n🚀 Multi-Mirror Accelerated Download & Fast Install\n🛡️ Cross-Device System Stability & Compatibility',
      'updateBtn': 'Fast In-App Update',
      'browserDownload': 'Browser Download',
      'laterBtn': 'Later',
      'downloadingTitle': 'Downloading ShareCLIP {version}',
      'downloadPreparing': 'Preparing download package...',
      'downloadConnecting': 'Connecting to high-speed mirror...',
      'downloadProgress': 'Downloading: {done} MB / {total} MB ({percent}%)',
      'downloadVerifying': 'Verifying package integrity...',
      'downloadInstalling': 'Download complete, launching installer...',
      'downloadFailed': 'Download Failed',
      'downloadFailedTip': 'Connection timed out. You can retry or download directly via browser.',
      'retryDownload': 'Retry Download',
    },
    'zh': {
      // Navigation & Shell
      'homeTitle': 'ShareCLIP 手机伴侣',
      'navLink': '连接',
      'navMedia': '相册',
      'navAi': 'AI相册',
      'navSettings': '设置',
      'aiCategories': '个分类',
      'aiNotSynced': '尚未同步 PC 矢量数据',
      'syncAiVectors': '同步 PC 矢量',
      'syncing': '同步中...',
      'aiThreshold': '置信度调节',
      'aiThresholdControl': '分类自由调节 (相似度阈值)',
      'aiMoreMatches': '匹配更广 (0.15)',
      'aiHigherPrecision': '精度更高 (0.45)',
      'aiNoCategoryPhotos': '该分类下暂未匹配到照片',
      'aiTryAdjustThreshold': '可尝试调低上方相似度滑块以放宽匹配',
      'aiWelcomeTitle': 'AI 智能相册分类 (端侧0计算)',
      'aiWelcomeDesc': '手机端不跑大模型，不发热不耗电！连接电脑后一键同步 PC 计算的特征矢量，即可享受分类自由与离线极速浏览。',
      'syncAiVectorsNow': '立即同步 PC 矢量数据',
      'aiConnectPcFirst': '请先连接电脑后再同步 AI 矢量数据',
      'disconnected': '未连接',
      'connected': '已连接',
      'linkPc': '扫码连接电脑',
      'linkPcDesc': '扫描 PC 客户端二维码建立直连同步',
      'scanToConnect': '扫码连接',
      'localMedia': '本地媒体',
      'items': '项',
      'photos': '照片',
      'videos': '视频',
      'music': '音乐',
      'docs': '文档',
      'queue': '队列',
      'noPhotos': '相册中暂无照片',
      'noVideos': '相册中暂无视频',
      'noMusic': '暂无本地音乐资源',
      'noDocs': '暂无已选择的文档',
      'pickDocs': '选择本地文档',
      'back': '返回',
      'backHome': '返回主页',
      'cancel': '取消',
      'retry': '重试连接',

      // Permissions
      'permissionTitle': '授权管理',
      'permissionDesc': '本应用需要摄像头权限扫码建立配对，并需要蓝牙与定位权限以通过蓝牙广播发现并与桌面管理端握手连接。',
      'grantBtn': '授予权限',
      'cameraPermRequired': '请在系统设置中授予相机权限以使用扫码功能',
      'cameraInitFailed': '相机初始化失败: {error}',

      // Connection Status & Steps
      'connecting': '正在连接电脑...',
      'connectingDesc': '正在通过蓝牙低功耗信令通道协商 WebRTC 握手参数。',
      'connFailed': '连接失败',
      'connFailedDesc': '无法与电脑成功配对，请检查电脑同步服务是否开启并重试。',
      'secureP2p': '安全点对点直连',
      'stepPairing': '发现与配对',
      'stepSignaling': '信令握手',
      'stepTunnel': '极速直连',
      'statusDiscovering': '正在通过局域网与蓝牙搜索电脑...',
      'statusMtu': '正在协商高速传输参数 (MTU)...',
      'statusGatt': '正在建立安全通信信道...',
      'statusCrypto': '正在生成 WebRTC 直连加密参数...',
      'statusOffer': '正在向电脑同步握手信令...',
      'statusAnswer': '正在等待电脑端确认连接...',
      'statusTunnel': '正在建立 P2P 极速加密直连传输通道...',
      'statusPreparing': '正在准备连接...',

      // Scanner & LAN
      'scannerBanner': '请将电脑端的二维码对准框内',
      'scanTitle': '扫码连接电脑',
      'scanSubTip': '将电脑端 ShareCLIP 二维码放入框内即可直连',
      'pickFromGallery': '相册选图',
      'torch': '补光灯',
      'flip': '翻转镜头',
      'lanPcFound': '局域网在线电脑',
      'instantConnect': '直连',
      'qrNotFound': '未能识别选定图片中的二维码',

      // Settings & Theme
      'settingsTitle': '设置与外观',
      'themeMode': '主题风格',
      'themeLight': '清爽亮色',
      'themeDark': '经典暗色',
      'themeOcean': '深海蓝调',
      'themeAmoled': '纯黑省电',
      'themeCyberpunk': '赛博朋克',
      'languageSettings': '语言设置',
      'selectLanguage': '选择语言',
      'currentLanguage': '当前语言',

      // Transfer Console & Sync Hub
      'tabMedia': '📸 媒体',
      'tabAi': '✨ AI相册',
      'tabMusic': '🎵 音乐',
      'tabDocs': '📄 文档',
      'tabQueue': '📥 队列',
      'aiVectorSyncTitle': '同步 PC 端 AI 矢量与分类',
      'aiVectorSyncDesc': '从电脑拉取已计算好的分类标准与特征向量，支持手机端离线分类自由与毫秒级筛选。',
      'syncAiVectorsBtn': '立即拉取 AI 矢量与分类',
      'syncingAiVectors': '正在从 PC 同步 AI 矢量数据...',
      'send': '发送',
      'receiving': '正在接收电脑文件...',
      'transmitting': '正在发送文件...',
      'queueEmpty': '暂无传输中的任务',
      'selectedPhotos': '已选照片',
      'selectedVideos': '已选视频',
      'selectedMusic': '已选音乐',
      'selectFilesHint': '前往其他选项卡勾选要传输的文件',
      'syncHub': '多端智能同步中心',
      'syncHubDesc': '多端极速数据同步与本地AI分类',
      'aiSyncTitle': 'AI 智能相册分类 (MobileCLIP)',
      'aiSyncDesc': '仅同步 400x400 高保真缩略图，PC 端秒级本地智能分类',
      'aiSyncProgress': 'AI分类同步中: {done}/{total}',
      'aiSyncDone': 'AI 分类同步已完成',
      'syncSelectedToAi': '同步选中 ({count}) 张图片到AI',
      'syncAllToAi': '同步全部图片到AI进行分类',
      'albumBackupTitle': '电脑端全量相册备份 (Full Backup)',
      'albumBackupDesc': '局域网 WebRTC 极速流式备份全量原始照片与视频',
      'albumBackupProgress': '全量备份中: {done}/{total} ({percent}%)',
      'albumBackupDone': '全量备份已完成',
      'resumeBackup': '继续备份',
      'pauseBackup': '暂停备份',
      'stopBackup': '停止备份',
      'startAlbumBackup': '开始全量备份相册到电脑',
      'resumeAlbumSync': '继续同步相册',
      'startVideoBackup': '开始备份全部视频到电脑',
      'resumeVideoSync': '继续同步视频',
      'startMusicBackup': '开始备份全部音乐到电脑',
      'resumeMusicSync': '继续同步音乐',

      // App Update & Downloader
      'updateTitle': '发现新版本',
      'updateSubtitle': '检测到全新版本可用',
      'updateMessage': '检测到 ShareCLIP 新版本 (v{version})，建议立即更新以获得更快的传输体验与稳定性加固。',
      'updateHighlights': '⚡ 极速 P2P 点对点传输与端侧 AI 增强\n🚀 多镜像 CDN 节点高速下载与免卸载安装\n🛡️ 全机型跨设备兼容性与系统深度加固',
      'updateBtn': '🚀 立即高速更新',
      'browserDownload': '🌐 浏览器下载',
      'laterBtn': '稍后提醒',
      'downloadingTitle': '正在高速下载 ShareCLIP {version}',
      'downloadPreparing': '准备下载安装包...',
      'downloadConnecting': '正在建立高速直连通道...',
      'downloadProgress': '正在下载: {done} MB / {total} MB ({percent}%)',
      'downloadVerifying': '正在校验安装包完整性...',
      'downloadInstalling': '下载完成，正在启动安装...',
      'downloadFailed': '⚠️ 下载未完成',
      'downloadFailedTip': '网络连接超时或镜像受限，建议使用手机自带浏览器直接下载。',
      'retryDownload': '重新下载',
    },
    'zh-TW': {
      // Navigation & Shell
      'homeTitle': 'ShareCLIP 手機伴侶',
      'navLink': '連線',
      'navMedia': '相簿',
      'navSettings': '設定',
      'disconnected': '未連線',
      'connected': '已連線',
      'linkPc': '掃碼連線電腦',
      'linkPcDesc': '掃描 PC 客戶端二維碼建立直連同步',
      'scanToConnect': '掃碼連線',
      'localMedia': '本地媒體',
      'items': '項',
      'photos': '照片',
      'videos': '影片',
      'music': '音樂',
      'docs': '文檔',
      'queue': '隊列',
      'noPhotos': '相簿中暫無照片',
      'noVideos': '相簿中暫無影片',
      'noMusic': '暫無本地音樂資源',
      'noDocs': '暫無已選擇的文檔',
      'pickDocs': '選擇本地文檔',
      'back': '返回',
      'backHome': '返回首頁',
      'cancel': '取消',
      'retry': '重試連線',

      // Permissions
      'permissionTitle': '授權管理',
      'permissionDesc': '本應用需要攝像頭權限掃碼建立配對，並需要藍牙與定位權限以通過藍牙廣播發現並與桌面管理端握手連線。',
      'grantBtn': '授權權限',
      'cameraPermRequired': '請在系統設定中授予相機權限以使用掃碼功能',
      'cameraInitFailed': '相機初始化失敗: {error}',

      // Connection Status & Steps
      'connecting': '正在連線電腦...',
      'connectingDesc': '正在通過藍牙低功耗信令通道協商 WebRTC 握手參數。',
      'connFailed': '連線失敗',
      'connFailedDesc': '無法與電腦成功配對，請檢查電腦同步服務是否開啟並重試。',
      'secureP2p': '安全點對點直連',
      'stepPairing': '發現與配對',
      'stepSignaling': '信令交握',
      'stepTunnel': '極速直連',
      'statusDiscovering': '正在透過區域網路與藍牙搜尋電腦...',
      'statusMtu': '正在協商高速傳輸參數 (MTU)...',
      'statusGatt': '正在建立安全通訊通道...',
      'statusCrypto': '正在生成 WebRTC 直連加密參數...',
      'statusOffer': '正在向電腦同步交握信令...',
      'statusAnswer': '正在等待電腦端確認連線...',
      'statusTunnel': '正在建立 P2P 極速加密直連傳輸通道...',
      'statusPreparing': '正在準備連線...',

      // Scanner & LAN
      'scannerBanner': '請將電腦端的二維碼對準框內',
      'scanTitle': '掃碼連線電腦',
      'scanSubTip': '將電腦端 ShareCLIP 二維碼放入框內即可直連',
      'pickFromGallery': '相簿選圖',
      'torch': '補光燈',
      'flip': '翻轉鏡頭',
      'lanPcFound': '區域網路在線電腦',
      'instantConnect': '直連',
      'qrNotFound': '未能識別選定圖片中的二維碼',

      // Settings & Theme
      'settingsTitle': '設定與外觀',
      'themeMode': '主題風格',
      'themeLight': '清爽亮色',
      'themeDark': '經典暗色',
      'themeOcean': '深海藍調',
      'themeAmoled': '純黑省電',
      'themeCyberpunk': '賽博朋克',
      'languageSettings': '語言設定',
      'selectLanguage': '選擇語言',
      'currentLanguage': '當前語言',

      // Transfer Console & Sync Hub
      'tabMedia': '📸 媒體',
      'tabMusic': '🎵 音樂',
      'tabDocs': '📄 文檔',
      'tabQueue': '📥 隊列',
      'send': '發送',
      'receiving': '正在接收電腦檔案...',
      'transmitting': '正在發送檔案...',
      'queueEmpty': '暫無傳輸中的任務',
      'selectedPhotos': '已選照片',
      'selectedVideos': '已選影片',
      'selectedMusic': '已選音樂',
      'selectFilesHint': '前往其他選項卡勾選要傳輸的檔案',
      'syncHub': '多端智慧同步中心',
      'syncHubDesc': '多端極速數據同步與本地AI分類',
      'aiSyncTitle': 'AI 智慧相簿分類 (MobileCLIP)',
      'aiSyncDesc': '僅同步 400x400 高保真縮略圖，PC 端秒級本地智慧分類',
      'aiSyncProgress': 'AI分類同步中: {done}/{total}',
      'aiSyncDone': 'AI 分類同步已完成',
      'syncSelectedToAi': '同步選中 ({count}) 張圖片到AI',
      'syncAllToAi': '同步全部圖片到AI進行分類',
      'albumBackupTitle': '電腦端全量相簿備份 (Full Backup)',
      'albumBackupDesc': '區域網路 WebRTC 極速串流備份全量原始照片與影片',
      'albumBackupProgress': '全量備份中: {done}/{total} ({percent}%)',
      'albumBackupDone': '全量備份已完成',
      'resumeBackup': '繼續備份',
      'pauseBackup': '暫停備份',
      'stopBackup': '停止備份',
      'startAlbumBackup': '開始全量備份相簿到電腦',
      'resumeAlbumSync': '繼續同步相簿',
      'startVideoBackup': '開始備份全部影片到電腦',
      'resumeVideoSync': '繼續同步影片',
      'startMusicBackup': '開始備份全部音樂到電腦',
      'resumeMusicSync': '繼續同步音樂',

      // App Update & Downloader
      'updateTitle': '發現新版本',
      'updateSubtitle': '檢測到全新版本可用',
      'updateMessage': '檢測到 ShareCLIP 新版本 (v{version})，建議立即更新以獲得更快的傳輸體驗與穩定性加固。',
      'updateHighlights': '⚡ 極速 P2P 點對點傳輸與端側 AI 增強\n🚀 多鏡像 CDN 節點高速下載與免卸載安裝\n🛡️ 全機型跨設備相容性與系統深度加固',
      'updateBtn': '🚀 立即高速更新',
      'browserDownload': '🌐 瀏覽器下載',
      'laterBtn': '稍後提醒',
      'downloadingTitle': '正在高速下載 ShareCLIP {version}',
      'downloadPreparing': '準備下載安裝包...',
      'downloadConnecting': '正在建立高速直連通道...',
      'downloadProgress': '正在下載: {done} MB / {total} MB ({percent}%)',
      'downloadVerifying': '正在校驗安裝包完整性...',
      'downloadInstalling': '下載完成，正在啟動安裝...',
      'downloadFailed': '⚠️ 下載未完成',
      'downloadFailedTip': '網路連線超時或鏡像受限，建議使用手機自帶瀏覽器直接下載。',
      'retryDownload': '重新下載',
    },
    'ja': {
      'homeTitle': 'ShareCLIP コンパニオン',
      'navLink': '接続',
      'navMedia': 'メディア',
      'navSettings': '設定',
      'disconnected': '未接続',
      'connected': '接続済み',
      'linkPc': 'QRコードで接続',
      'linkPcDesc': 'PCのQRコードをスキャンして同期を開始',
      'scanToConnect': 'QRスキャン',
      'localMedia': 'ローカルメディア',
      'items': '件',
      'photos': '写真',
      'videos': '動画',
      'music': '音楽',
      'docs': 'ドキュメント',
      'queue': 'キュー',
      'noPhotos': '写真がありません',
      'noVideos': '動画がありません',
      'noMusic': '音楽がありません',
      'noDocs': 'ドキュメントがありません',
      'pickDocs': 'ファイルを選択',
      'back': '戻る',
      'backHome': 'ホームに戻る',
      'cancel': 'キャンセル',
      'retry': '再試行',
      'permissionTitle': '権限の許可',
      'permissionDesc': 'QRコードのスキャンとBluetooth/Wi-Fiペアリングのためにカメラと権限が必要です。',
      'grantBtn': '権限を許可',
      'cameraPermRequired': '設定でカメラの権限を許可してください',
      'cameraInitFailed': 'カメラの初期化に失敗しました: {error}',
      'connecting': 'PCに接続中...',
      'connectingDesc': 'Bluetooth経由でWebRTCパラメータを交換しています。',
      'connFailed': '接続失敗',
      'connFailedDesc': 'PCとペアリングできませんでした。接続を確認してください。',
      'secureP2p': 'セキュア P2P 同期',
      'stepPairing': '検出とペアリング',
      'stepSignaling': 'ハンドシェイク',
      'stepTunnel': 'P2P直結',
      'statusDiscovering': 'LANおよびBluetoothでPCを探索中...',
      'statusMtu': '高速MTUパラメータを交渉中...',
      'statusGatt': '安全なサービスチャネルを確立中...',
      'statusCrypto': 'WebRTC暗号化パラメータを生成中...',
      'statusOffer': 'PCにハンドシェイクを送信中...',
      'statusAnswer': 'PCの応答を待機中...',
      'statusTunnel': 'P2P高速暗号化トンネルを構築中...',
      'statusPreparing': '接続を準備中...',
      'scannerBanner': 'PC画面のQRコードを枠に合わせてください',
      'scanTitle': 'QRコードでPC接続',
      'scanSubTip': 'PCのQRコードを枠に合わせると即座に接続します',
      'pickFromGallery': 'アルバムから選択',
      'torch': 'ライト',
      'flip': 'カメラ切替',
      'lanPcFound': '周辺のLAN PC',
      'instantConnect': '接続',
      'qrNotFound': '画像からQRコードが検出されませんでした',
      'settingsTitle': '設定と外観',
      'themeMode': 'テーマ',
      'themeLight': 'ライト',
      'themeDark': 'ダーク',
      'themeOcean': 'オーシャン',
      'themeAmoled': 'AMOLEDピュアブラック',
      'themeCyberpunk': 'サイバーパンク',
      'languageSettings': '言語設定',
      'selectLanguage': '言語を選択',
      'currentLanguage': '現在の言語',
      'tabMedia': '📸 メディア',
      'tabMusic': '🎵 音楽',
      'tabDocs': '📄 文書',
      'tabQueue': '📥 キュー',
      'send': '送信',
      'receiving': 'ファイル受信中...',
      'transmitting': 'ファイル送信中...',
      'queueEmpty': '転送タスクはありません',
      'selectedPhotos': '選択した写真',
      'selectedVideos': '選択した動画',
      'selectedMusic': '選択した音楽',
      'selectFilesHint': '他のタブから転送するファイルを選択してください',
      'syncHub': 'スマート同期センター',
      'syncHubDesc': '高速P2Pデータ同期とAI分類',
      'aiSyncTitle': 'AIアルバム分類 (MobileCLIP)',
      'aiSyncDesc': 'サムネイルのみをPCに同期し高速AI分類を実行',
      'aiSyncProgress': 'AI同期中: {done}/{total}',
      'aiSyncDone': 'AI同期完了',
      'syncSelectedToAi': '選択した ({count}) 枚をAI同期',
      'syncAllToAi': 'すべての画像をAI同期',
      'albumBackupTitle': 'PCフルアルバムバックアップ',
      'albumBackupDesc': '全写真・動画をローカルP2Pでフルバックアップ',
      'albumBackupProgress': 'バックアップ中: {done}/{total} ({percent}%)',
      'albumBackupDone': 'バックアップ完了',
      'resumeBackup': '再開',
      'pauseBackup': '一時停止',
      'stopBackup': '停止',
      'startAlbumBackup': 'フルバックアップ開始',
      'resumeAlbumSync': 'アルバム同期再開',
      'startVideoBackup': 'すべての動画をバックアップ',
      'resumeVideoSync': '動画同期再開',
      'startMusicBackup': 'すべての音楽をバックアップ',
      'resumeMusicSync': '音楽同期再開',
      'updateTitle': '新しいバージョン',
      'updateSubtitle': '新バージョンが利用可能です',
      'updateMessage': 'ShareCLIP (v{version}) が利用可能です。今すぐ更新しますか？',
      'updateHighlights': '⚡ 超高速P2P転送とAI機能の強化\n🚀 マルチミラー高速ダウンロード\n🛡️ 互換性と安定性の向上',
      'updateBtn': '🚀 今すぐ高速更新',
      'browserDownload': '🌐 ブラウザでダウンロード',
      'laterBtn': '後で',
      'downloadingTitle': 'ShareCLIP {version} をダウンロード中',
      'downloadPreparing': 'ダウンロード準備中...',
      'downloadConnecting': '高速ミラーに接続中...',
      'downloadProgress': 'ダウンロード中: {done} MB / {total} MB ({percent}%)',
      'downloadVerifying': 'パッケージ整合性を検証中...',
      'downloadInstalling': 'ダウンロード完了、インストーラーを起動中...',
      'downloadFailed': '⚠️ ダウンロード未完了',
      'downloadFailedTip': '接続がタイムアウトしました。ブラウザからの直接ダウンロードをお勧めします。',
      'retryDownload': '再試行',
    },
    'ko': {
      'homeTitle': 'ShareCLIP 컴패니언',
      'navLink': '연결',
      'navMedia': '미디어',
      'navSettings': '설정',
      'disconnected': '연결 안 됨',
      'connected': '연결됨',
      'linkPc': 'QR 코드로 PC 연결',
      'linkPcDesc': 'PC 화면의 QR 코드를 스캔하여 동기화 시작',
      'scanToConnect': 'QR 스캔',
      'localMedia': '로컬 미디어',
      'items': '개',
      'photos': '사진',
      'videos': '비디오',
      'music': '음악',
      'docs': '문서',
      'queue': '대기열',
      'noPhotos': '사진이 없습니다',
      'noVideos': '동영상이 없습니다',
      'noMusic': '음악이 없습니다',
      'noDocs': '선택된 문서가 없습니다',
      'pickDocs': '문서 선택',
      'back': '뒤로',
      'backHome': '홈으로 돌아가기',
      'cancel': '취소',
      'retry': '재시도',
      'permissionTitle': '권한 허용',
      'permissionDesc': 'QR 코드 스캔 및 블루투스/Wi-Fi 연결을 위해 권한이 필요합니다.',
      'grantBtn': '권한 허용',
      'cameraPermRequired': '설정에서 카메라 권한을 허용해 주세요',
      'cameraInitFailed': '카메라 초기화 실패: {error}',
      'connecting': 'PC에 연결 중...',
      'connectingDesc': '블루투스를 통해 WebRTC 매개변수를 교환하는 중입니다.',
      'connFailed': '연결 실패',
      'connFailedDesc': 'PC와 페어링할 수 없습니다. 설정을 확인해 주세요.',
      'secureP2p': '보안 P2P 직접 연결',
      'stepPairing': '발견 및 페어링',
      'stepSignaling': '핸드셰이크',
      'stepTunnel': 'P2P 직결',
      'statusDiscovering': 'LAN 및 블루투스로 PC 검색 중...',
      'statusMtu': '고속 MTU 매개변수 협상 중...',
      'statusGatt': '보안 서비스 채널 구축 중...',
      'statusCrypto': 'WebRTC 암호화 매개변수 생성 중...',
      'statusOffer': 'PC로 핸드셰이크 신호 전송 중...',
      'statusAnswer': 'PC 확인 대기 중...',
      'statusTunnel': 'P2P 고속 암호화 터널 생성 중...',
      'statusPreparing': '연결 준비 중...',
      'scannerBanner': 'PC의 QR 코드를 프레임에 맞춰주세요',
      'scanTitle': 'QR 스캔하여 PC 연결',
      'scanSubTip': 'PC의 QR 코드를 프레임에 맞추면 즉시 연결됩니다',
      'pickFromGallery': '갤러리에서 선택',
      'torch': '손전등',
      'flip': '카메라 전환',
      'lanPcFound': '주변 LAN PC',
      'instantConnect': '연결',
      'qrNotFound': '선택한 이미지에서 QR 코드를 찾을 수 없습니다',
      'settingsTitle': '설정 및 모양',
      'themeMode': '테마 스타일',
      'themeLight': '라이트',
      'themeDark': '다크',
      'themeOcean': '오션 블루',
      'themeAmoled': 'AMOLED 퓨어 블랙',
      'themeCyberpunk': '사이버펑크',
      'languageSettings': '언어 설정',
      'selectLanguage': '언어 선택',
      'currentLanguage': '현재 언어',
      'tabMedia': '📸 미디어',
      'tabMusic': '🎵 음악',
      'tabDocs': '📄 문서',
      'tabQueue': '📥 대기열',
      'send': '전송',
      'receiving': '파일 수신 중...',
      'transmitting': '파일 전송 중...',
      'queueEmpty': '전송 중인 작업 없음',
      'selectedPhotos': '선택한 사진',
      'selectedVideos': '선택한 동영상',
      'selectedMusic': '선택한 음악',
      'selectFilesHint': '다른 탭에서 전송할 파일을 선택하세요',
      'syncHub': '스마트 동기화 센터',
      'syncHubDesc': '초고속 P2P 데이터 동기화 및 AI 분류',
      'aiSyncTitle': 'AI 앨범 분류 (MobileCLIP)',
      'aiSyncDesc': '썸네일만 PC로 전송하여 로컬 AI 자동 분류',
      'aiSyncProgress': 'AI 동기화 중: {done}/{total}',
      'aiSyncDone': 'AI 동기화 완료',
      'syncSelectedToAi': '선택한 ({count})장 AI 동기화',
      'syncAllToAi': '모든 사진 AI 동기화',
      'albumBackupTitle': 'PC 전체 앨범 백업',
      'albumBackupDesc': '모든 원본 사진 및 비디오를 P2P로 완전 백업',
      'albumBackupProgress': '백업 중: {done}/{total} ({percent}%)',
      'albumBackupDone': '백업 완료',
      'resumeBackup': '계속',
      'pauseBackup': '일시 중지',
      'stopBackup': '중지',
      'startAlbumBackup': '전체 앨범 백업 시작',
      'resumeAlbumSync': '앨범 동기화 재개',
      'startVideoBackup': '모든 동영상 백업',
      'resumeVideoSync': '동영상 동기화 재개',
      'startMusicBackup': '모든 음악 백업',
      'resumeMusicSync': '음악 동기화 재개',
      'updateTitle': '새 버전 발견',
      'updateSubtitle': '새로운 버전이 출시되었습니다',
      'updateMessage': 'ShareCLIP 새 버전 (v{version})을 사용할 수 있습니다. 지금 업데이트하시겠습니까?',
      'updateHighlights': '⚡ 초고속 P2P 전송 및 AI 분류 강화\n🚀 다중 미러 가속 다운로드\n🛡️ 호환성 및 시스템 안정성 향상',
      'updateBtn': '🚀 지금 고속 업데이트',
      'browserDownload': '🌐 브라우저로 다운로드',
      'laterBtn': '나중에',
      'downloadingTitle': 'ShareCLIP {version} 다운로드 중',
      'downloadPreparing': '설치 패키지 준비 중...',
      'downloadConnecting': '고속 미러 연결 중...',
      'downloadProgress': '다운로드 중: {done} MB / {total} MB ({percent}%)',
      'downloadVerifying': '패키지 무결성 검증 중...',
      'downloadInstalling': '다운로드 완료, 설치 프로그램 시작 중...',
      'downloadFailed': '⚠️ 다운로드 실패',
      'downloadFailedTip': '네트워크 연결이 지연되었습니다. 브라우저로 직접 다운로드하는 것을 권장합니다.',
      'retryDownload': '다시 시도',
    }
  };

  String get(String key) {
    if (_locales[_currentLocale]?.containsKey(key) ?? false) {
      return _locales[_currentLocale]![key]!;
    }
    // Fallback to English
    return _locales['en']![key] ?? key;
  }

  Future<void> setLanguage(String langCode) async {
    if (!languages.containsKey(langCode)) return;
    _currentLocale = langCode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keyLang, langCode);
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString(_keyLang);
    if (savedLang != null && languages.containsKey(savedLang)) {
      _currentLocale = savedLang;
      notifyListeners();
    }
  }

  // Prepopulate other languages with English clone tags to guarantee safety
  static void initializeLocales() {
    languages.forEach((code, name) {
      if (!_locales.containsKey(code)) {
        final cloned = Map<String, String>.from(_locales['en']!);
        _locales[code] = cloned;
      }
    });
  }
}

// Run static initializer
final _initialized = () {
  LocalizationService.initializeLocales();
  return true;
}();
